### ISSUE TITLE
Set up pre releases with covector/changesets

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/material-ui-interactors#6]
We'll soon have a preview of interactors that we can ship, and so we should try to get them out the door now, so that they'll be waiting and ready on npm when it's time to rip some code.

**Comment by jbolda** [comment]
In chatting with @elrickvm, we thought that we would need to release alpha/beta/rc prereleases leading up to the major version. We are considering this because we want our releases to sync with `material-ui` major versions. Covector has "beta" support for the prereleases finally. We can start implementing it if we are getting close to release. If not, we can implement it once the prerelease functionality makes it into the "stable" release of covector.

**Comment by cowboyd** [comment]
@jbolda The sooner we can get these out the door, the better. I know that's not the greatest answer in how to prioritize life, but if we can start making an `4.0.0-alpha.x` release series that would be amazing.

Also, implementing the current as `v1` is an option as a stand-in for alpha because the first version of material-ui that we're targeting is `v4` (althoug they are on the cusp of releasing v5). That means that between v0 and v4 we have 3 major versions that we can burn. 

Would that be the best option for now?

**Comment by cowboyd** [comment]
As an aside, knowing what I now know about the special cases added to 0.x in semver, I'm much more short on it.

Feels to me like the best practice going forward would be to just start with `1.0.0-dev` Thoughts?

**Comment by jbolda** [comment]
> The sooner we can get these out the door, the better. I know that's not the greatest answer in how to prioritize life, but if we can start making an `4.0.0-alpha.x` release series that would be amazing.

Sure, we can run it off of the branch for now. It seems to be working pretty well, and the main thing that hasn't been addressed is the npm publish tag (which we will publish on `--latest` here, which is the default). I also added some guardrails that can throw an error if we try to bump to something we don't want.

> Feels to me like the best practice going forward would be to just start with 1.0.0-dev Thoughts?

I think `-dev` would actually sort after alpha/beta. I believe the capitalized version of that would work though, `-DEV.x`. I am tempted to say, <1.0.0 is fine, but just avoid prereleases in that case. Prereleases in general have a bunch of special considerations.
